version: '3'

services:

    nginx:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

            # SSL/TLS certificates
            - ./certs:/etc/nginx/certs

            # Custom virtualhost configurations
            - ./vhost.d:/etc/nginx/vhost.d

            # Custom add-ons for index page
            - ./custom/index.conf:/etc/nginx/conf.d/index.conf
            - ./custom/index.tmpl:/app/index.tmpl
            - ./custom/Procfile:/app/Procfile
