version: '3'

services:

    nginx:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./sites:/etc/nginx/conf.d
            - ./certs:/etc/nginx/certs
        networks:
            - shared_default

networks:
  shared_default:
    external: true
