version: '3'

services:

    nginx:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./sites:/etc/nginx/conf.d
            - ./certs:/etc/nginx/certs
            - ./Procfile:/app/Procfile
            - ./www:/var/www
