dockergen: docker-gen -watch -notify "nginx -s reload" /app/nginx.tmpl /etc/nginx/conf.d/default.conf
dockergen: docker-gen -watch                           /app/index.tmpl /usr/share/nginx/html/index.html
nginx: nginx
